[package]
name = "flame"
version = "0.1.6"
authors = ["Ty Overby <ty@pre-alpha.com>"]
license = "MIT/Apache-2.0"
exclude = ["resources/*.png"]

description = "a profiling / flamegraph library"
repository = "https://github.com/TyOverby/flame"
documentation = "http://tyoverby.com/flame/flame/index.html"

[dependencies]
